/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proxy_ConnectionManager */

#ifndef _Included_proxy_ConnectionManager
#define _Included_proxy_ConnectionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     proxy_ConnectionManager
 * Method:    register
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_proxy_ConnectionManager_register
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
